#ifndef LIBYOUTILSPRECOMPILEDHEADER_H_HXX
#define LIBYOUTILSPRECOMPILEDHEADER_H_HXX
#ifndef NO_PRECOMPILED_HEADERS
#include <assert.h>
#include <stdio.h>
#include <errno.h>
#include <math.h>
#include <features.h>
#include <algorithm>
// youtils
#include <pstreams/pstream.h>
#include "BooleanEnum.h"
// standard c++ lib
#include <functional>
#include <future>
#include <memory>
#include <atomic>
#include <exception>
#include <string>
#include <map>
#include <vector>
// Loki
#include <loki/Typelist.h>
// CORBA
#include <omniORB4/CORBA.h>
// BOOST LOGGING
#include <boost/program_options.hpp>
#include <boost/log/sources/severity_logger.hpp>
#include <boost/log/sources/record_ostream.hpp>
#include <boost/date_time.hpp>
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
#include <boost/thread.hpp>
#include <boost/bimap.hpp>
#include <boost/filesystem.hpp>
#include <boost/property_tree/ptree_fwd.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/bimap/unordered_set_of.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/mpl/assert.hpp>
#include <boost/serialization/wrapper.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/scope_exit.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/serialization/list.hpp>
#endif // NO_PRECOMPILED_HEADERS
#endif // LIBYOUTILSPRECOMPILEDHEADER_H_HXX
